spring.application.name=userdatamanage

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/userdatamanage
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Server Configuration
server.port=8081

#logger
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=ERROR
logging.level.sql=trace

#JWT Configuration
jwt.secret=546A576E5A7234753778214125442A472D4A614E645267556B58703273357638
jwt.refresh.expiration=604800000


#swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha  
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.filter=true
springdoc.packages-to-scan=com.usermanage.userdatamanage
springdoc.paths-to-match=/api/**